name: ci
on: push
jobs:
  credo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{github.job}}-${{matrix.elixir}}-${{matrix.otp}}-${{hashFiles('mix.lock')}}-1
          path: _build
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix credo --strict --ignore todo
    strategy:
      matrix:
        elixir: ['1.15.x', '1.16.x', '1.17.x']
        otp: ['24.x', '25.x', '26.x', '27.x']
        exclude:
          - elixir: '1.15.x'
            otp: '27.x'
          - elixir: '1.16.x'
            otp: '27.x'
          - elixir: '1.17.x'
            otp: '24.x'

  dialyzer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          key: ${{github.job}}-${{matrix.elixir}}-${{matrix.otp}}-${{hashFiles('mix.lock')}}-1
          path: _build
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix dialyzer
    strategy:
      matrix:
        elixir: ['1.15.x', '1.16.x', '1.17.x']
        otp: ['24.x', '25.x', '26.x', '27.x']
        exclude:
          - elixir: '1.15.x'
            otp: '27.x'
          - elixir: '1.16.x'
            otp: '27.x'
          - elixir: '1.17.x'
            otp: '24.x'
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          key: ${{github.job}}-${{matrix.elixir}}-${{matrix.otp}}-${{hashFiles('mix.lock')}}-1
          path: _build
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
    strategy:
      matrix:
        elixir: ['1.15.x', '1.16.x', '1.17.x']
        otp: ['24.x', '25.x', '26.x', '27.x']
        exclude:
          - elixir: '1.15.x'
            otp: '27.x'
          - elixir: '1.16.x'
            otp: '27.x'
          - elixir: '1.17.x'
            otp: '24.x'
